language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
    - julia: 1.0
    - julia: 0.6
notifications:
  email: false
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("JWAS")); include(joinpath("docs", "make.jl"))'
# uncomment the following lines to override the default test script
#script:
# - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
# - julia -e 'ENV["PYTHON"] = ""; Pkg.clone("PyPlot"); Pkg.build("PyPlot")' #for linux
# - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("JWAS"); Pkg.test("JWAS"; coverage=true)'
